// Code generated by MockGen. DO NOT EDIT.
// Source: internal/mcp/shared/registry.go
//
// Generated by this command:
//
//	mockgen -source=internal/mcp/shared/registry.go -destination=internal/mocks/mock_session_registry.go -package=mocks SessionRegistry
//

// Package mocks is a generated GoMock package.
package mocks
