// Code generated by MockGen. DO NOT EDIT.
// Source: ../manager/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../manager/interfaces.go -destination=mock_manager.go -package=mocks ProjectManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/denkhaus/knot/v2/internal/config"
	types "github.com/denkhaus/knot/v2/internal/types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectManager is a mock of ProjectManager interface.
type MockProjectManager struct {
	ctrl     *gomock.Controller
	recorder *MockProjectManagerMockRecorder
	isgomock struct{}
}

// MockProjectManagerMockRecorder is the mock recorder for MockProjectManager.
type MockProjectManagerMockRecorder struct {
	mock *MockProjectManager
}

// NewMockProjectManager creates a new mock instance.
func NewMockProjectManager(ctrl *gomock.Controller) *MockProjectManager {
	mock := &MockProjectManager{ctrl: ctrl}
	mock.recorder = &MockProjectManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectManager) EXPECT() *MockProjectManagerMockRecorder {
	return m.recorder
}

// AddTaskDependency mocks base method.
func (m *MockProjectManager) AddTaskDependency(ctx context.Context, taskID, dependsOnTaskID uuid.UUID, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskDependency", ctx, taskID, dependsOnTaskID, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTaskDependency indicates an expected call of AddTaskDependency.
func (mr *MockProjectManagerMockRecorder) AddTaskDependency(ctx, taskID, dependsOnTaskID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskDependency", reflect.TypeOf((*MockProjectManager)(nil).AddTaskDependency), ctx, taskID, dependsOnTaskID, actor)
}

// AssignTaskToAgent mocks base method.
func (m *MockProjectManager) AssignTaskToAgent(ctx context.Context, taskID, agentID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTaskToAgent", ctx, taskID, agentID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTaskToAgent indicates an expected call of AssignTaskToAgent.
func (mr *MockProjectManagerMockRecorder) AssignTaskToAgent(ctx, taskID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTaskToAgent", reflect.TypeOf((*MockProjectManager)(nil).AssignTaskToAgent), ctx, taskID, agentID)
}

// BulkUpdateTasks mocks base method.
func (m *MockProjectManager) BulkUpdateTasks(ctx context.Context, taskIDs []uuid.UUID, updates types.TaskUpdates, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateTasks", ctx, taskIDs, updates, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateTasks indicates an expected call of BulkUpdateTasks.
func (mr *MockProjectManagerMockRecorder) BulkUpdateTasks(ctx, taskIDs, updates, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateTasks", reflect.TypeOf((*MockProjectManager)(nil).BulkUpdateTasks), ctx, taskIDs, updates, actor)
}

// ClearSelectedProject mocks base method.
func (m *MockProjectManager) ClearSelectedProject(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSelectedProject", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSelectedProject indicates an expected call of ClearSelectedProject.
func (mr *MockProjectManagerMockRecorder) ClearSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSelectedProject", reflect.TypeOf((*MockProjectManager)(nil).ClearSelectedProject), ctx)
}

// CreateProject mocks base method.
func (m *MockProjectManager) CreateProject(ctx context.Context, title, description, actor string) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, title, description, actor)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectManagerMockRecorder) CreateProject(ctx, title, description, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectManager)(nil).CreateProject), ctx, title, description, actor)
}

// CreateTask mocks base method.
func (m *MockProjectManager) CreateTask(ctx context.Context, projectID uuid.UUID, parentID *uuid.UUID, title, description string, complexity int, priority types.TaskPriority, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, projectID, parentID, title, description, complexity, priority, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockProjectManagerMockRecorder) CreateTask(ctx, projectID, parentID, title, description, complexity, priority, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockProjectManager)(nil).CreateTask), ctx, projectID, parentID, title, description, complexity, priority, actor)
}

// DeleteProject mocks base method.
func (m *MockProjectManager) DeleteProject(ctx context.Context, projectID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectManagerMockRecorder) DeleteProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectManager)(nil).DeleteProject), ctx, projectID)
}

// DeleteTask mocks base method.
func (m *MockProjectManager) DeleteTask(ctx context.Context, taskID uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockProjectManagerMockRecorder) DeleteTask(ctx, taskID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockProjectManager)(nil).DeleteTask), ctx, taskID, actor)
}

// DeleteTaskSubtree mocks base method.
func (m *MockProjectManager) DeleteTaskSubtree(ctx context.Context, taskID uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskSubtree", ctx, taskID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskSubtree indicates an expected call of DeleteTaskSubtree.
func (mr *MockProjectManagerMockRecorder) DeleteTaskSubtree(ctx, taskID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskSubtree", reflect.TypeOf((*MockProjectManager)(nil).DeleteTaskSubtree), ctx, taskID, actor)
}

// DuplicateTask mocks base method.
func (m *MockProjectManager) DuplicateTask(ctx context.Context, taskID, newProjectID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DuplicateTask", ctx, taskID, newProjectID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DuplicateTask indicates an expected call of DuplicateTask.
func (mr *MockProjectManagerMockRecorder) DuplicateTask(ctx, taskID, newProjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DuplicateTask", reflect.TypeOf((*MockProjectManager)(nil).DuplicateTask), ctx, taskID, newProjectID)
}

// FindNextActionableTask mocks base method.
func (m *MockProjectManager) FindNextActionableTask(ctx context.Context, projectID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNextActionableTask", ctx, projectID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNextActionableTask indicates an expected call of FindNextActionableTask.
func (mr *MockProjectManagerMockRecorder) FindNextActionableTask(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNextActionableTask", reflect.TypeOf((*MockProjectManager)(nil).FindNextActionableTask), ctx, projectID)
}

// FindTasksNeedingBreakdown mocks base method.
func (m *MockProjectManager) FindTasksNeedingBreakdown(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTasksNeedingBreakdown", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTasksNeedingBreakdown indicates an expected call of FindTasksNeedingBreakdown.
func (mr *MockProjectManagerMockRecorder) FindTasksNeedingBreakdown(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTasksNeedingBreakdown", reflect.TypeOf((*MockProjectManager)(nil).FindTasksNeedingBreakdown), ctx, projectID)
}

// GetChildTasks mocks base method.
func (m *MockProjectManager) GetChildTasks(ctx context.Context, taskID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChildTasks", ctx, taskID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChildTasks indicates an expected call of GetChildTasks.
func (mr *MockProjectManagerMockRecorder) GetChildTasks(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChildTasks", reflect.TypeOf((*MockProjectManager)(nil).GetChildTasks), ctx, taskID)
}

// GetConfig mocks base method.
func (m *MockProjectManager) GetConfig() *config.ManagerConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(*config.ManagerConfig)
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockProjectManagerMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockProjectManager)(nil).GetConfig))
}

// GetCurrentTime mocks base method.
func (m *MockProjectManager) GetCurrentTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetCurrentTime indicates an expected call of GetCurrentTime.
func (mr *MockProjectManagerMockRecorder) GetCurrentTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentTime", reflect.TypeOf((*MockProjectManager)(nil).GetCurrentTime))
}

// GetDependentTasks mocks base method.
func (m *MockProjectManager) GetDependentTasks(ctx context.Context, taskID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependentTasks", ctx, taskID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDependentTasks indicates an expected call of GetDependentTasks.
func (mr *MockProjectManagerMockRecorder) GetDependentTasks(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependentTasks", reflect.TypeOf((*MockProjectManager)(nil).GetDependentTasks), ctx, taskID)
}

// GetParentTask mocks base method.
func (m *MockProjectManager) GetParentTask(ctx context.Context, taskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentTask", ctx, taskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentTask indicates an expected call of GetParentTask.
func (mr *MockProjectManagerMockRecorder) GetParentTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentTask", reflect.TypeOf((*MockProjectManager)(nil).GetParentTask), ctx, taskID)
}

// GetProject mocks base method.
func (m *MockProjectManager) GetProject(ctx context.Context, projectID uuid.UUID) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, projectID)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockProjectManagerMockRecorder) GetProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockProjectManager)(nil).GetProject), ctx, projectID)
}

// GetProjectProgress mocks base method.
func (m *MockProjectManager) GetProjectProgress(ctx context.Context, projectID uuid.UUID) (*types.ProjectProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectProgress", ctx, projectID)
	ret0, _ := ret[0].(*types.ProjectProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectProgress indicates an expected call of GetProjectProgress.
func (mr *MockProjectManagerMockRecorder) GetProjectProgress(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectProgress", reflect.TypeOf((*MockProjectManager)(nil).GetProjectProgress), ctx, projectID)
}

// GetRootTasks mocks base method.
func (m *MockProjectManager) GetRootTasks(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRootTasks", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRootTasks indicates an expected call of GetRootTasks.
func (mr *MockProjectManagerMockRecorder) GetRootTasks(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootTasks", reflect.TypeOf((*MockProjectManager)(nil).GetRootTasks), ctx, projectID)
}

// GetSelectedProject mocks base method.
func (m *MockProjectManager) GetSelectedProject(ctx context.Context) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectedProject", ctx)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedProject indicates an expected call of GetSelectedProject.
func (mr *MockProjectManagerMockRecorder) GetSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedProject", reflect.TypeOf((*MockProjectManager)(nil).GetSelectedProject), ctx)
}

// GetTask mocks base method.
func (m *MockProjectManager) GetTask(ctx context.Context, taskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, taskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockProjectManagerMockRecorder) GetTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockProjectManager)(nil).GetTask), ctx, taskID)
}

// GetTaskDependencies mocks base method.
func (m *MockProjectManager) GetTaskDependencies(ctx context.Context, taskID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskDependencies", ctx, taskID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskDependencies indicates an expected call of GetTaskDependencies.
func (mr *MockProjectManagerMockRecorder) GetTaskDependencies(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskDependencies", reflect.TypeOf((*MockProjectManager)(nil).GetTaskDependencies), ctx, taskID)
}

// GetTasksWithDependencies mocks base method.
func (m *MockProjectManager) GetTasksWithDependencies(ctx context.Context, taskIDs []uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksWithDependencies", ctx, taskIDs)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksWithDependencies indicates an expected call of GetTasksWithDependencies.
func (mr *MockProjectManagerMockRecorder) GetTasksWithDependencies(ctx, taskIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithDependencies", reflect.TypeOf((*MockProjectManager)(nil).GetTasksWithDependencies), ctx, taskIDs)
}

// HasSelectedProject mocks base method.
func (m *MockProjectManager) HasSelectedProject(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSelectedProject", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSelectedProject indicates an expected call of HasSelectedProject.
func (mr *MockProjectManagerMockRecorder) HasSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSelectedProject", reflect.TypeOf((*MockProjectManager)(nil).HasSelectedProject), ctx)
}

// HealthCheck mocks base method.
func (m *MockProjectManager) HealthCheck(ctx context.Context) (*types.HealthStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(*types.HealthStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockProjectManagerMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockProjectManager)(nil).HealthCheck), ctx)
}

// ListProjects mocks base method.
func (m *MockProjectManager) ListProjects(ctx context.Context) ([]*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx)
	ret0, _ := ret[0].([]*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectManagerMockRecorder) ListProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectManager)(nil).ListProjects), ctx)
}

// ListTasksByAgent mocks base method.
func (m *MockProjectManager) ListTasksByAgent(ctx context.Context, projectID, agentID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasksByAgent", ctx, projectID, agentID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasksByAgent indicates an expected call of ListTasksByAgent.
func (mr *MockProjectManagerMockRecorder) ListTasksByAgent(ctx, projectID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasksByAgent", reflect.TypeOf((*MockProjectManager)(nil).ListTasksByAgent), ctx, projectID, agentID)
}

// ListTasksByState mocks base method.
func (m *MockProjectManager) ListTasksByState(ctx context.Context, projectID uuid.UUID, state types.TaskState) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasksByState", ctx, projectID, state)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasksByState indicates an expected call of ListTasksByState.
func (mr *MockProjectManagerMockRecorder) ListTasksByState(ctx, projectID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasksByState", reflect.TypeOf((*MockProjectManager)(nil).ListTasksByState), ctx, projectID, state)
}

// ListTasksForProject mocks base method.
func (m *MockProjectManager) ListTasksForProject(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasksForProject", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasksForProject indicates an expected call of ListTasksForProject.
func (mr *MockProjectManagerMockRecorder) ListTasksForProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasksForProject", reflect.TypeOf((*MockProjectManager)(nil).ListTasksForProject), ctx, projectID)
}

// ListUnassignedTasks mocks base method.
func (m *MockProjectManager) ListUnassignedTasks(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnassignedTasks", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnassignedTasks indicates an expected call of ListUnassignedTasks.
func (mr *MockProjectManagerMockRecorder) ListUnassignedTasks(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnassignedTasks", reflect.TypeOf((*MockProjectManager)(nil).ListUnassignedTasks), ctx, projectID)
}

// LoadConfigFromFile mocks base method.
func (m *MockProjectManager) LoadConfigFromFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadConfigFromFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadConfigFromFile indicates an expected call of LoadConfigFromFile.
func (mr *MockProjectManagerMockRecorder) LoadConfigFromFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadConfigFromFile", reflect.TypeOf((*MockProjectManager)(nil).LoadConfigFromFile))
}

// Ping mocks base method.
func (m *MockProjectManager) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockProjectManagerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockProjectManager)(nil).Ping), ctx)
}

// RemoveTaskDependency mocks base method.
func (m *MockProjectManager) RemoveTaskDependency(ctx context.Context, taskID, dependsOnTaskID uuid.UUID, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTaskDependency", ctx, taskID, dependsOnTaskID, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTaskDependency indicates an expected call of RemoveTaskDependency.
func (mr *MockProjectManagerMockRecorder) RemoveTaskDependency(ctx, taskID, dependsOnTaskID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTaskDependency", reflect.TypeOf((*MockProjectManager)(nil).RemoveTaskDependency), ctx, taskID, dependsOnTaskID, actor)
}

// ResolveProjectID mocks base method.
func (m *MockProjectManager) ResolveProjectID(ctx context.Context) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveProjectID", ctx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveProjectID indicates an expected call of ResolveProjectID.
func (mr *MockProjectManagerMockRecorder) ResolveProjectID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveProjectID", reflect.TypeOf((*MockProjectManager)(nil).ResolveProjectID), ctx)
}

// SaveConfigToFile mocks base method.
func (m *MockProjectManager) SaveConfigToFile() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveConfigToFile")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveConfigToFile indicates an expected call of SaveConfigToFile.
func (mr *MockProjectManagerMockRecorder) SaveConfigToFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConfigToFile", reflect.TypeOf((*MockProjectManager)(nil).SaveConfigToFile))
}

// SetSelectedProject mocks base method.
func (m *MockProjectManager) SetSelectedProject(ctx context.Context, projectID uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSelectedProject", ctx, projectID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSelectedProject indicates an expected call of SetSelectedProject.
func (mr *MockProjectManagerMockRecorder) SetSelectedProject(ctx, projectID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSelectedProject", reflect.TypeOf((*MockProjectManager)(nil).SetSelectedProject), ctx, projectID, actor)
}

// SetTaskEstimate mocks base method.
func (m *MockProjectManager) SetTaskEstimate(ctx context.Context, taskID uuid.UUID, estimate int64) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTaskEstimate", ctx, taskID, estimate)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTaskEstimate indicates an expected call of SetTaskEstimate.
func (mr *MockProjectManagerMockRecorder) SetTaskEstimate(ctx, taskID, estimate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTaskEstimate", reflect.TypeOf((*MockProjectManager)(nil).SetTaskEstimate), ctx, taskID, estimate)
}

// SyncCreateProjectWithTimestamps mocks base method.
func (m *MockProjectManager) SyncCreateProjectWithTimestamps(ctx context.Context, project *types.Project) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncCreateProjectWithTimestamps", ctx, project)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncCreateProjectWithTimestamps indicates an expected call of SyncCreateProjectWithTimestamps.
func (mr *MockProjectManagerMockRecorder) SyncCreateProjectWithTimestamps(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCreateProjectWithTimestamps", reflect.TypeOf((*MockProjectManager)(nil).SyncCreateProjectWithTimestamps), ctx, project)
}

// SyncCreateTaskWithTimestamps mocks base method.
func (m *MockProjectManager) SyncCreateTaskWithTimestamps(ctx context.Context, task *types.Task) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncCreateTaskWithTimestamps", ctx, task)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncCreateTaskWithTimestamps indicates an expected call of SyncCreateTaskWithTimestamps.
func (mr *MockProjectManagerMockRecorder) SyncCreateTaskWithTimestamps(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncCreateTaskWithTimestamps", reflect.TypeOf((*MockProjectManager)(nil).SyncCreateTaskWithTimestamps), ctx, task)
}

// UnassignTaskFromAgent mocks base method.
func (m *MockProjectManager) UnassignTaskFromAgent(ctx context.Context, taskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignTaskFromAgent", ctx, taskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnassignTaskFromAgent indicates an expected call of UnassignTaskFromAgent.
func (mr *MockProjectManagerMockRecorder) UnassignTaskFromAgent(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignTaskFromAgent", reflect.TypeOf((*MockProjectManager)(nil).UnassignTaskFromAgent), ctx, taskID)
}

// UpdateConfig mocks base method.
func (m *MockProjectManager) UpdateConfig(arg0 *config.ManagerConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateConfig", arg0)
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockProjectManagerMockRecorder) UpdateConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockProjectManager)(nil).UpdateConfig), arg0)
}

// UpdateProject mocks base method.
func (m *MockProjectManager) UpdateProject(ctx context.Context, projectID uuid.UUID, title, description, actor string) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, projectID, title, description, actor)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectManagerMockRecorder) UpdateProject(ctx, projectID, title, description, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectManager)(nil).UpdateProject), ctx, projectID, title, description, actor)
}

// UpdateProjectDescription mocks base method.
func (m *MockProjectManager) UpdateProjectDescription(ctx context.Context, projectID uuid.UUID, description, actor string) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectDescription", ctx, projectID, description, actor)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectDescription indicates an expected call of UpdateProjectDescription.
func (mr *MockProjectManagerMockRecorder) UpdateProjectDescription(ctx, projectID, description, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectDescription", reflect.TypeOf((*MockProjectManager)(nil).UpdateProjectDescription), ctx, projectID, description, actor)
}

// UpdateProjectState mocks base method.
func (m *MockProjectManager) UpdateProjectState(ctx context.Context, projectID uuid.UUID, state types.ProjectState, actor string) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectState", ctx, projectID, state, actor)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectState indicates an expected call of UpdateProjectState.
func (mr *MockProjectManagerMockRecorder) UpdateProjectState(ctx, projectID, state, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectState", reflect.TypeOf((*MockProjectManager)(nil).UpdateProjectState), ctx, projectID, state, actor)
}

// UpdateTask mocks base method.
func (m *MockProjectManager) UpdateTask(ctx context.Context, taskID uuid.UUID, title, description string, complexity int, state types.TaskState, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, taskID, title, description, complexity, state, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockProjectManagerMockRecorder) UpdateTask(ctx, taskID, title, description, complexity, state, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockProjectManager)(nil).UpdateTask), ctx, taskID, title, description, complexity, state, actor)
}

// UpdateTaskComplexity mocks base method.
func (m *MockProjectManager) UpdateTaskComplexity(ctx context.Context, taskID uuid.UUID, complexity int, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskComplexity", ctx, taskID, complexity, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskComplexity indicates an expected call of UpdateTaskComplexity.
func (mr *MockProjectManagerMockRecorder) UpdateTaskComplexity(ctx, taskID, complexity, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskComplexity", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskComplexity), ctx, taskID, complexity, actor)
}

// UpdateTaskDescription mocks base method.
func (m *MockProjectManager) UpdateTaskDescription(ctx context.Context, taskID uuid.UUID, description, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskDescription", ctx, taskID, description, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskDescription indicates an expected call of UpdateTaskDescription.
func (mr *MockProjectManagerMockRecorder) UpdateTaskDescription(ctx, taskID, description, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskDescription", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskDescription), ctx, taskID, description, actor)
}

// UpdateTaskForSync mocks base method.
func (m *MockProjectManager) UpdateTaskForSync(ctx context.Context, task *types.Task) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskForSync", ctx, task)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskForSync indicates an expected call of UpdateTaskForSync.
func (mr *MockProjectManagerMockRecorder) UpdateTaskForSync(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskForSync", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskForSync), ctx, task)
}

// UpdateTaskPriority mocks base method.
func (m *MockProjectManager) UpdateTaskPriority(ctx context.Context, taskID uuid.UUID, priority types.TaskPriority, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskPriority", ctx, taskID, priority, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskPriority indicates an expected call of UpdateTaskPriority.
func (mr *MockProjectManagerMockRecorder) UpdateTaskPriority(ctx, taskID, priority, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskPriority", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskPriority), ctx, taskID, priority, actor)
}

// UpdateTaskState mocks base method.
func (m *MockProjectManager) UpdateTaskState(ctx context.Context, taskID uuid.UUID, state types.TaskState, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskState", ctx, taskID, state, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskState indicates an expected call of UpdateTaskState.
func (mr *MockProjectManagerMockRecorder) UpdateTaskState(ctx, taskID, state, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskState", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskState), ctx, taskID, state, actor)
}

// UpdateTaskTitle mocks base method.
func (m *MockProjectManager) UpdateTaskTitle(ctx context.Context, taskID uuid.UUID, title, actor string) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskTitle", ctx, taskID, title, actor)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskTitle indicates an expected call of UpdateTaskTitle.
func (mr *MockProjectManagerMockRecorder) UpdateTaskTitle(ctx, taskID, title, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskTitle", reflect.TypeOf((*MockProjectManager)(nil).UpdateTaskTitle), ctx, taskID, title, actor)
}

// ValidateConnection mocks base method.
func (m *MockProjectManager) ValidateConnection(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnection", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateConnection indicates an expected call of ValidateConnection.
func (mr *MockProjectManagerMockRecorder) ValidateConnection(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnection", reflect.TypeOf((*MockProjectManager)(nil).ValidateConnection), ctx)
}
