// Code generated by MockGen. DO NOT EDIT.
// Source: ../mcp/shared/registry.go
//
// Generated by this command:
//
//	mockgen -source=../mcp/shared/registry.go -destination=mock_session_registry.go -package=mocks SessionRegistry
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	shared "github.com/denkhaus/knot/v2/internal/mcp/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRegistry is a mock of SessionRegistry interface.
type MockSessionRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRegistryMockRecorder
	isgomock struct{}
}

// MockSessionRegistryMockRecorder is the mock recorder for MockSessionRegistry.
type MockSessionRegistryMockRecorder struct {
	mock *MockSessionRegistry
}

// NewMockSessionRegistry creates a new mock instance.
func NewMockSessionRegistry(ctrl *gomock.Controller) *MockSessionRegistry {
	mock := &MockSessionRegistry{ctrl: ctrl}
	mock.recorder = &MockSessionRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRegistry) EXPECT() *MockSessionRegistryMockRecorder {
	return m.recorder
}

// CleanupExpiredSessions mocks base method.
func (m *MockSessionRegistry) CleanupExpiredSessions(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredSessions", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockSessionRegistryMockRecorder) CleanupExpiredSessions(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockSessionRegistry)(nil).CleanupExpiredSessions), ctx, timeout)
}

// GetOrCreateSession mocks base method.
func (m *MockSessionRegistry) GetOrCreateSession(ctx context.Context, sessionID uuid.UUID) (*shared.MCPClientSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateSession", ctx, sessionID)
	ret0, _ := ret[0].(*shared.MCPClientSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateSession indicates an expected call of GetOrCreateSession.
func (mr *MockSessionRegistryMockRecorder) GetOrCreateSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateSession", reflect.TypeOf((*MockSessionRegistry)(nil).GetOrCreateSession), ctx, sessionID)
}

// GetSession mocks base method.
func (m *MockSessionRegistry) GetSession(sessionID uuid.UUID) (*shared.MCPClientSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*shared.MCPClientSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionRegistryMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionRegistry)(nil).GetSession), sessionID)
}

// GetSessionCount mocks base method.
func (m *MockSessionRegistry) GetSessionCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSessionCount indicates an expected call of GetSessionCount.
func (mr *MockSessionRegistryMockRecorder) GetSessionCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionCount", reflect.TypeOf((*MockSessionRegistry)(nil).GetSessionCount))
}

// RemoveSession mocks base method.
func (m *MockSessionRegistry) RemoveSession(ctx context.Context, sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockSessionRegistryMockRecorder) RemoveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockSessionRegistry)(nil).RemoveSession), ctx, sessionID)
}

// SetSessionProject mocks base method.
func (m *MockSessionRegistry) SetSessionProject(ctx context.Context, sessionID uuid.UUID, projectID *uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionProject", ctx, sessionID, projectID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSessionProject indicates an expected call of SetSessionProject.
func (mr *MockSessionRegistryMockRecorder) SetSessionProject(ctx, sessionID, projectID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionProject", reflect.TypeOf((*MockSessionRegistry)(nil).SetSessionProject), ctx, sessionID, projectID, actor)
}

// SyncExistingSessions mocks base method.
func (m *MockSessionRegistry) SyncExistingSessions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncExistingSessions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncExistingSessions indicates an expected call of SyncExistingSessions.
func (mr *MockSessionRegistryMockRecorder) SyncExistingSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncExistingSessions", reflect.TypeOf((*MockSessionRegistry)(nil).SyncExistingSessions), ctx)
}
