// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/service.go -destination=internal/mocks/mock_config_service.go -package=mocks Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/denkhaus/knot/v2/internal/config"
	cli "github.com/urfave/cli/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetConfigPath mocks base method.
func (m *MockService) GetConfigPath() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigPath")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigPath indicates an expected call of GetConfigPath.
func (mr *MockServiceMockRecorder) GetConfigPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigPath", reflect.TypeOf((*MockService)(nil).GetConfigPath))
}

// GetDatabasePath mocks base method.
func (m *MockService) GetDatabasePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabasePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabasePath indicates an expected call of GetDatabasePath.
func (mr *MockServiceMockRecorder) GetDatabasePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabasePath", reflect.TypeOf((*MockService)(nil).GetDatabasePath))
}

// GetLogLevel mocks base method.
func (m *MockService) GetLogLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLogLevel indicates an expected call of GetLogLevel.
func (mr *MockServiceMockRecorder) GetLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLevel", reflect.TypeOf((*MockService)(nil).GetLogLevel))
}

// GetMCPConfig mocks base method.
func (m *MockService) GetMCPConfig() *config.MCPConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMCPConfig")
	ret0, _ := ret[0].(*config.MCPConfig)
	return ret0
}

// GetMCPConfig indicates an expected call of GetMCPConfig.
func (mr *MockServiceMockRecorder) GetMCPConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMCPConfig", reflect.TypeOf((*MockService)(nil).GetMCPConfig))
}

// GetManagerConfig mocks base method.
func (m *MockService) GetManagerConfig() *config.ManagerConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagerConfig")
	ret0, _ := ret[0].(*config.ManagerConfig)
	return ret0
}

// GetManagerConfig indicates an expected call of GetManagerConfig.
func (mr *MockServiceMockRecorder) GetManagerConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagerConfig", reflect.TypeOf((*MockService)(nil).GetManagerConfig))
}

// GetPostgresEndpoint mocks base method.
func (m *MockService) GetPostgresEndpoint(c *cli.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostgresEndpoint", c)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPostgresEndpoint indicates an expected call of GetPostgresEndpoint.
func (mr *MockServiceMockRecorder) GetPostgresEndpoint(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostgresEndpoint", reflect.TypeOf((*MockService)(nil).GetPostgresEndpoint), c)
}

// GetSyncConfig mocks base method.
func (m *MockService) GetSyncConfig() *config.SyncConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncConfig")
	ret0, _ := ret[0].(*config.SyncConfig)
	return ret0
}

// GetSyncConfig indicates an expected call of GetSyncConfig.
func (mr *MockServiceMockRecorder) GetSyncConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncConfig", reflect.TypeOf((*MockService)(nil).GetSyncConfig))
}

// GetTemplatesPath mocks base method.
func (m *MockService) GetTemplatesPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplatesPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTemplatesPath indicates an expected call of GetTemplatesPath.
func (mr *MockServiceMockRecorder) GetTemplatesPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplatesPath", reflect.TypeOf((*MockService)(nil).GetTemplatesPath))
}

// InitializeFromCLIContext mocks base method.
func (m *MockService) InitializeFromCLIContext(c *cli.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeFromCLIContext", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeFromCLIContext indicates an expected call of InitializeFromCLIContext.
func (mr *MockServiceMockRecorder) InitializeFromCLIContext(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeFromCLIContext", reflect.TypeOf((*MockService)(nil).InitializeFromCLIContext), c)
}

// IsMCPMode mocks base method.
func (m *MockService) IsMCPMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMCPMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMCPMode indicates an expected call of IsMCPMode.
func (mr *MockServiceMockRecorder) IsMCPMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMCPMode", reflect.TypeOf((*MockService)(nil).IsMCPMode))
}

// SetDatabasePath mocks base method.
func (m *MockService) SetDatabasePath(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDatabasePath", path)
}

// SetDatabasePath indicates an expected call of SetDatabasePath.
func (mr *MockServiceMockRecorder) SetDatabasePath(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatabasePath", reflect.TypeOf((*MockService)(nil).SetDatabasePath), path)
}

// SetLogLevel mocks base method.
func (m *MockService) SetLogLevel(level string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogLevel", level)
}

// SetLogLevel indicates an expected call of SetLogLevel.
func (mr *MockServiceMockRecorder) SetLogLevel(level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogLevel", reflect.TypeOf((*MockService)(nil).SetLogLevel), level)
}

// SetMCPConfig mocks base method.
func (m *MockService) SetMCPConfig(arg0 *config.MCPConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMCPConfig", arg0)
}

// SetMCPConfig indicates an expected call of SetMCPConfig.
func (mr *MockServiceMockRecorder) SetMCPConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMCPConfig", reflect.TypeOf((*MockService)(nil).SetMCPConfig), arg0)
}

// SetMCPMode mocks base method.
func (m *MockService) SetMCPMode(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMCPMode", enabled)
}

// SetMCPMode indicates an expected call of SetMCPMode.
func (mr *MockServiceMockRecorder) SetMCPMode(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMCPMode", reflect.TypeOf((*MockService)(nil).SetMCPMode), enabled)
}

// SetManagerConfig mocks base method.
func (m *MockService) SetManagerConfig(arg0 *config.ManagerConfig) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetManagerConfig", arg0)
}

// SetManagerConfig indicates an expected call of SetManagerConfig.
func (mr *MockServiceMockRecorder) SetManagerConfig(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetManagerConfig", reflect.TypeOf((*MockService)(nil).SetManagerConfig), arg0)
}
