// Code generated by MockGen. DO NOT EDIT.
// Source: ../sync/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=../sync/interfaces.go -destination=mock_sync_manager.go -package=mocks SyncManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sync "github.com/denkhaus/knot/v2/internal/sync"
	shared "github.com/denkhaus/knot/v2/internal/sync/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncManager is a mock of SyncManager interface.
type MockSyncManager struct {
	ctrl     *gomock.Controller
	recorder *MockSyncManagerMockRecorder
	isgomock struct{}
}

// MockSyncManagerMockRecorder is the mock recorder for MockSyncManager.
type MockSyncManagerMockRecorder struct {
	mock *MockSyncManager
}

// NewMockSyncManager creates a new mock instance.
func NewMockSyncManager(ctrl *gomock.Controller) *MockSyncManager {
	mock := &MockSyncManager{ctrl: ctrl}
	mock.recorder = &MockSyncManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncManager) EXPECT() *MockSyncManagerMockRecorder {
	return m.recorder
}

// SyncBidirectional mocks base method.
func (m *MockSyncManager) SyncBidirectional(ctx context.Context, localData *shared.SyncDataSet) (*sync.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncBidirectional", ctx, localData)
	ret0, _ := ret[0].(*sync.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncBidirectional indicates an expected call of SyncBidirectional.
func (mr *MockSyncManagerMockRecorder) SyncBidirectional(ctx, localData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncBidirectional", reflect.TypeOf((*MockSyncManager)(nil).SyncBidirectional), ctx, localData)
}

// SyncPullFromRemote mocks base method.
func (m *MockSyncManager) SyncPullFromRemote(ctx context.Context, projectID uuid.UUID) (*sync.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPullFromRemote", ctx, projectID)
	ret0, _ := ret[0].(*sync.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncPullFromRemote indicates an expected call of SyncPullFromRemote.
func (mr *MockSyncManagerMockRecorder) SyncPullFromRemote(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPullFromRemote", reflect.TypeOf((*MockSyncManager)(nil).SyncPullFromRemote), ctx, projectID)
}

// SyncWithLocalData mocks base method.
func (m *MockSyncManager) SyncWithLocalData(ctx context.Context, localData *shared.SyncDataSet) (*sync.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncWithLocalData", ctx, localData)
	ret0, _ := ret[0].(*sync.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncWithLocalData indicates an expected call of SyncWithLocalData.
func (mr *MockSyncManagerMockRecorder) SyncWithLocalData(ctx, localData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncWithLocalData", reflect.TypeOf((*MockSyncManager)(nil).SyncWithLocalData), ctx, localData)
}
