// Code generated by MockGen. DO NOT EDIT.
// Source: internal/types/types.go
//
// Generated by this command:
//
//	mockgen -source=internal/types/types.go -destination=internal/mocks/mock_repository_provider.go -package=mocks RepositoryProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/denkhaus/knot/v2/internal/types"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddTaskDependency mocks base method.
func (m *MockRepository) AddTaskDependency(ctx context.Context, taskID, dependsOnTaskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskDependency", ctx, taskID, dependsOnTaskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTaskDependency indicates an expected call of AddTaskDependency.
func (mr *MockRepositoryMockRecorder) AddTaskDependency(ctx, taskID, dependsOnTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskDependency", reflect.TypeOf((*MockRepository)(nil).AddTaskDependency), ctx, taskID, dependsOnTaskID)
}

// ClearSelectedProject mocks base method.
func (m *MockRepository) ClearSelectedProject(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSelectedProject", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSelectedProject indicates an expected call of ClearSelectedProject.
func (mr *MockRepositoryMockRecorder) ClearSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSelectedProject", reflect.TypeOf((*MockRepository)(nil).ClearSelectedProject), ctx)
}

// CreateProject mocks base method.
func (m *MockRepository) CreateProject(ctx context.Context, project *types.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProject", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockRepositoryMockRecorder) CreateProject(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockRepository)(nil).CreateProject), ctx, project)
}

// CreateTask mocks base method.
func (m *MockRepository) CreateTask(ctx context.Context, task *types.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockRepositoryMockRecorder) CreateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockRepository)(nil).CreateTask), ctx, task)
}

// DeleteProject mocks base method.
func (m *MockRepository) DeleteProject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockRepositoryMockRecorder) DeleteProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockRepository)(nil).DeleteProject), ctx, id)
}

// DeleteTask mocks base method.
func (m *MockRepository) DeleteTask(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepositoryMockRecorder) DeleteTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepository)(nil).DeleteTask), ctx, id)
}

// DeleteTaskSubtree mocks base method.
func (m *MockRepository) DeleteTaskSubtree(ctx context.Context, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTaskSubtree", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTaskSubtree indicates an expected call of DeleteTaskSubtree.
func (mr *MockRepositoryMockRecorder) DeleteTaskSubtree(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTaskSubtree", reflect.TypeOf((*MockRepository)(nil).DeleteTaskSubtree), ctx, taskID)
}

// GetDependentTasks mocks base method.
func (m *MockRepository) GetDependentTasks(ctx context.Context, taskID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependentTasks", ctx, taskID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDependentTasks indicates an expected call of GetDependentTasks.
func (mr *MockRepositoryMockRecorder) GetDependentTasks(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependentTasks", reflect.TypeOf((*MockRepository)(nil).GetDependentTasks), ctx, taskID)
}

// GetParentTask mocks base method.
func (m *MockRepository) GetParentTask(ctx context.Context, taskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentTask", ctx, taskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentTask indicates an expected call of GetParentTask.
func (mr *MockRepositoryMockRecorder) GetParentTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentTask", reflect.TypeOf((*MockRepository)(nil).GetParentTask), ctx, taskID)
}

// GetProject mocks base method.
func (m *MockRepository) GetProject(ctx context.Context, id uuid.UUID) (*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", ctx, id)
	ret0, _ := ret[0].(*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockRepositoryMockRecorder) GetProject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockRepository)(nil).GetProject), ctx, id)
}

// GetProjectProgress mocks base method.
func (m *MockRepository) GetProjectProgress(ctx context.Context, projectID uuid.UUID) (*types.ProjectProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectProgress", ctx, projectID)
	ret0, _ := ret[0].(*types.ProjectProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectProgress indicates an expected call of GetProjectProgress.
func (mr *MockRepositoryMockRecorder) GetProjectProgress(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectProgress", reflect.TypeOf((*MockRepository)(nil).GetProjectProgress), ctx, projectID)
}

// GetRootTasks mocks base method.
func (m *MockRepository) GetRootTasks(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRootTasks", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRootTasks indicates an expected call of GetRootTasks.
func (mr *MockRepositoryMockRecorder) GetRootTasks(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootTasks", reflect.TypeOf((*MockRepository)(nil).GetRootTasks), ctx, projectID)
}

// GetSelectedProject mocks base method.
func (m *MockRepository) GetSelectedProject(ctx context.Context) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectedProject", ctx)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedProject indicates an expected call of GetSelectedProject.
func (mr *MockRepositoryMockRecorder) GetSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedProject", reflect.TypeOf((*MockRepository)(nil).GetSelectedProject), ctx)
}

// GetTask mocks base method.
func (m *MockRepository) GetTask(ctx context.Context, id uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, id)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockRepositoryMockRecorder) GetTask(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockRepository)(nil).GetTask), ctx, id)
}

// GetTaskCountByDepth mocks base method.
func (m *MockRepository) GetTaskCountByDepth(ctx context.Context, projectID uuid.UUID, maxDepth int) (map[int]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskCountByDepth", ctx, projectID, maxDepth)
	ret0, _ := ret[0].(map[int]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskCountByDepth indicates an expected call of GetTaskCountByDepth.
func (mr *MockRepositoryMockRecorder) GetTaskCountByDepth(ctx, projectID, maxDepth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskCountByDepth", reflect.TypeOf((*MockRepository)(nil).GetTaskCountByDepth), ctx, projectID, maxDepth)
}

// GetTaskDependencies mocks base method.
func (m *MockRepository) GetTaskDependencies(ctx context.Context, taskID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskDependencies", ctx, taskID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskDependencies indicates an expected call of GetTaskDependencies.
func (mr *MockRepositoryMockRecorder) GetTaskDependencies(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskDependencies", reflect.TypeOf((*MockRepository)(nil).GetTaskDependencies), ctx, taskID)
}

// GetTasksByParent mocks base method.
func (m *MockRepository) GetTasksByParent(ctx context.Context, parentID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByParent", ctx, parentID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByParent indicates an expected call of GetTasksByParent.
func (mr *MockRepositoryMockRecorder) GetTasksByParent(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByParent", reflect.TypeOf((*MockRepository)(nil).GetTasksByParent), ctx, parentID)
}

// GetTasksByProject mocks base method.
func (m *MockRepository) GetTasksByProject(ctx context.Context, projectID uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksByProject", ctx, projectID)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksByProject indicates an expected call of GetTasksByProject.
func (mr *MockRepositoryMockRecorder) GetTasksByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksByProject", reflect.TypeOf((*MockRepository)(nil).GetTasksByProject), ctx, projectID)
}

// GetTasksWithDependencies mocks base method.
func (m *MockRepository) GetTasksWithDependencies(ctx context.Context, taskIDs []uuid.UUID) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksWithDependencies", ctx, taskIDs)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksWithDependencies indicates an expected call of GetTasksWithDependencies.
func (mr *MockRepositoryMockRecorder) GetTasksWithDependencies(ctx, taskIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksWithDependencies", reflect.TypeOf((*MockRepository)(nil).GetTasksWithDependencies), ctx, taskIDs)
}

// HasSelectedProject mocks base method.
func (m *MockRepository) HasSelectedProject(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasSelectedProject", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasSelectedProject indicates an expected call of HasSelectedProject.
func (mr *MockRepositoryMockRecorder) HasSelectedProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasSelectedProject", reflect.TypeOf((*MockRepository)(nil).HasSelectedProject), ctx)
}

// ListProjects mocks base method.
func (m *MockRepository) ListProjects(ctx context.Context) ([]*types.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", ctx)
	ret0, _ := ret[0].([]*types.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockRepositoryMockRecorder) ListProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockRepository)(nil).ListProjects), ctx)
}

// ListTasks mocks base method.
func (m *MockRepository) ListTasks(ctx context.Context, filter types.TaskFilter) ([]*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", ctx, filter)
	ret0, _ := ret[0].([]*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockRepositoryMockRecorder) ListTasks(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockRepository)(nil).ListTasks), ctx, filter)
}

// RemoveTaskDependency mocks base method.
func (m *MockRepository) RemoveTaskDependency(ctx context.Context, taskID, dependsOnTaskID uuid.UUID) (*types.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTaskDependency", ctx, taskID, dependsOnTaskID)
	ret0, _ := ret[0].(*types.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveTaskDependency indicates an expected call of RemoveTaskDependency.
func (mr *MockRepositoryMockRecorder) RemoveTaskDependency(ctx, taskID, dependsOnTaskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTaskDependency", reflect.TypeOf((*MockRepository)(nil).RemoveTaskDependency), ctx, taskID, dependsOnTaskID)
}

// SetSelectedProject mocks base method.
func (m *MockRepository) SetSelectedProject(ctx context.Context, projectID uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSelectedProject", ctx, projectID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSelectedProject indicates an expected call of SetSelectedProject.
func (mr *MockRepositoryMockRecorder) SetSelectedProject(ctx, projectID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSelectedProject", reflect.TypeOf((*MockRepository)(nil).SetSelectedProject), ctx, projectID, actor)
}

// UpdateProject mocks base method.
func (m *MockRepository) UpdateProject(ctx context.Context, project *types.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProject", ctx, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockRepositoryMockRecorder) UpdateProject(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockRepository)(nil).UpdateProject), ctx, project)
}

// UpdateTask mocks base method.
func (m *MockRepository) UpdateTask(ctx context.Context, task *types.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockRepositoryMockRecorder) UpdateTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockRepository)(nil).UpdateTask), ctx, task)
}

// MockRepositoryProvider is a mock of RepositoryProvider interface.
type MockRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryProviderMockRecorder
	isgomock struct{}
}

// MockRepositoryProviderMockRecorder is the mock recorder for MockRepositoryProvider.
type MockRepositoryProviderMockRecorder struct {
	mock *MockRepositoryProvider
}

// NewMockRepositoryProvider creates a new mock instance.
func NewMockRepositoryProvider(ctrl *gomock.Controller) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryProvider) EXPECT() *MockRepositoryProviderMockRecorder {
	return m.recorder
}

// NewRepository mocks base method.
func (m *MockRepositoryProvider) NewRepository(dsn string, opts ...any) (types.Repository, error) {
	m.ctrl.T.Helper()
	varargs := []any{dsn}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewRepository", varargs...)
	ret0, _ := ret[0].(types.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRepository indicates an expected call of NewRepository.
func (mr *MockRepositoryProviderMockRecorder) NewRepository(dsn any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{dsn}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRepository", reflect.TypeOf((*MockRepositoryProvider)(nil).NewRepository), varargs...)
}
