// Code generated by MockGen. DO NOT EDIT.
// Source: ../sync/client/client.go
//
// Generated by this command:
//
//	mockgen -source=../sync/client/client.go -destination=mock_sync_rest_client.go -package=mocks RESTSyncClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/denkhaus/knot/v2/internal/sync/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRESTSyncClient is a mock of RESTSyncClient interface.
type MockRESTSyncClient struct {
	ctrl     *gomock.Controller
	recorder *MockRESTSyncClientMockRecorder
	isgomock struct{}
}

// MockRESTSyncClientMockRecorder is the mock recorder for MockRESTSyncClient.
type MockRESTSyncClientMockRecorder struct {
	mock *MockRESTSyncClient
}

// NewMockRESTSyncClient creates a new mock instance.
func NewMockRESTSyncClient(ctrl *gomock.Controller) *MockRESTSyncClient {
	mock := &MockRESTSyncClient{ctrl: ctrl}
	mock.recorder = &MockRESTSyncClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRESTSyncClient) EXPECT() *MockRESTSyncClientMockRecorder {
	return m.recorder
}

// GetProjects mocks base method.
func (m *MockRESTSyncClient) GetProjects(ctx context.Context) (*shared.SyncDataSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjects", ctx)
	ret0, _ := ret[0].(*shared.SyncDataSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjects indicates an expected call of GetProjects.
func (mr *MockRESTSyncClientMockRecorder) GetProjects(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjects", reflect.TypeOf((*MockRESTSyncClient)(nil).GetProjects), ctx)
}

// GetRemoteData mocks base method.
func (m *MockRESTSyncClient) GetRemoteData(ctx context.Context, projectID *uuid.UUID) (*shared.SyncDataSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteData", ctx, projectID)
	ret0, _ := ret[0].(*shared.SyncDataSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteData indicates an expected call of GetRemoteData.
func (mr *MockRESTSyncClientMockRecorder) GetRemoteData(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteData", reflect.TypeOf((*MockRESTSyncClient)(nil).GetRemoteData), ctx, projectID)
}

// GetTasks mocks base method.
func (m *MockRESTSyncClient) GetTasks(ctx context.Context, projectID uuid.UUID) (*shared.SyncDataSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, projectID)
	ret0, _ := ret[0].(*shared.SyncDataSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockRESTSyncClientMockRecorder) GetTasks(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockRESTSyncClient)(nil).GetTasks), ctx, projectID)
}

// HealthCheck mocks base method.
func (m *MockRESTSyncClient) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockRESTSyncClientMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockRESTSyncClient)(nil).HealthCheck), ctx)
}

// Sync mocks base method.
func (m *MockRESTSyncClient) Sync(ctx context.Context, req *shared.SyncRequest) (*shared.SyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, req)
	ret0, _ := ret[0].(*shared.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockRESTSyncClientMockRecorder) Sync(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockRESTSyncClient)(nil).Sync), ctx, req)
}
