// Code generated by MockGen. DO NOT EDIT.
// Source: ../mcp/hints/interface.go
//
// Generated by this command:
//
//	mockgen -source=../mcp/hints/interface.go -destination=mock_hint_integration.go -package=mocks Integration
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	manager "github.com/denkhaus/knot/v2/internal/manager"
	hints "github.com/denkhaus/knot/v2/internal/mcp/hints"
	session "github.com/denkhaus/knot/v2/internal/session"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
	isgomock struct{}
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// FilterHints mocks base method.
func (m *MockGenerator) FilterHints(arg0 []hints.Hint) []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterHints", arg0)
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// FilterHints indicates an expected call of FilterHints.
func (mr *MockGeneratorMockRecorder) FilterHints(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterHints", reflect.TypeOf((*MockGenerator)(nil).FilterHints), arg0)
}

// GenerateGeneralHints mocks base method.
func (m *MockGenerator) GenerateGeneralHints() []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateGeneralHints")
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// GenerateGeneralHints indicates an expected call of GenerateGeneralHints.
func (mr *MockGeneratorMockRecorder) GenerateGeneralHints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateGeneralHints", reflect.TypeOf((*MockGenerator)(nil).GenerateGeneralHints))
}

// GenerateHints mocks base method.
func (m *MockGenerator) GenerateHints(ctx context.Context, toolName string, result any, sessionState *hints.SessionState) []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHints", ctx, toolName, result, sessionState)
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// GenerateHints indicates an expected call of GenerateHints.
func (mr *MockGeneratorMockRecorder) GenerateHints(ctx, toolName, result, sessionState any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHints", reflect.TypeOf((*MockGenerator)(nil).GenerateHints), ctx, toolName, result, sessionState)
}

// GenerateNoProjectSelectedHints mocks base method.
func (m *MockGenerator) GenerateNoProjectSelectedHints() []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNoProjectSelectedHints")
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// GenerateNoProjectSelectedHints indicates an expected call of GenerateNoProjectSelectedHints.
func (mr *MockGeneratorMockRecorder) GenerateNoProjectSelectedHints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNoProjectSelectedHints", reflect.TypeOf((*MockGenerator)(nil).GenerateNoProjectSelectedHints))
}

// MockIntegration is a mock of Integration interface.
type MockIntegration struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationMockRecorder
	isgomock struct{}
}

// MockIntegrationMockRecorder is the mock recorder for MockIntegration.
type MockIntegrationMockRecorder struct {
	mock *MockIntegration
}

// NewMockIntegration creates a new mock instance.
func NewMockIntegration(ctrl *gomock.Controller) *MockIntegration {
	mock := &MockIntegration{ctrl: ctrl}
	mock.recorder = &MockIntegrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegration) EXPECT() *MockIntegrationMockRecorder {
	return m.recorder
}

// FormatHintsForOutput mocks base method.
func (m *MockIntegration) FormatHintsForOutput(arg0 []hints.Hint) []any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatHintsForOutput", arg0)
	ret0, _ := ret[0].([]any)
	return ret0
}

// FormatHintsForOutput indicates an expected call of FormatHintsForOutput.
func (mr *MockIntegrationMockRecorder) FormatHintsForOutput(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatHintsForOutput", reflect.TypeOf((*MockIntegration)(nil).FormatHintsForOutput), arg0)
}

// GenerateContextualHints mocks base method.
func (m *MockIntegration) GenerateContextualHints(ctx context.Context, projectManager manager.ProjectManager, sessionManager session.SessionManager) []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateContextualHints", ctx, projectManager, sessionManager)
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// GenerateContextualHints indicates an expected call of GenerateContextualHints.
func (mr *MockIntegrationMockRecorder) GenerateContextualHints(ctx, projectManager, sessionManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateContextualHints", reflect.TypeOf((*MockIntegration)(nil).GenerateContextualHints), ctx, projectManager, sessionManager)
}

// GenerateToolHints mocks base method.
func (m *MockIntegration) GenerateToolHints(ctx context.Context, toolName string, result any, projectManager manager.ProjectManager, sessionManager session.SessionManager) []hints.Hint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToolHints", ctx, toolName, result, projectManager, sessionManager)
	ret0, _ := ret[0].([]hints.Hint)
	return ret0
}

// GenerateToolHints indicates an expected call of GenerateToolHints.
func (mr *MockIntegrationMockRecorder) GenerateToolHints(ctx, toolName, result, projectManager, sessionManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToolHints", reflect.TypeOf((*MockIntegration)(nil).GenerateToolHints), ctx, toolName, result, projectManager, sessionManager)
}

// GetHintStats mocks base method.
func (m *MockIntegration) GetHintStats() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHintStats")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetHintStats indicates an expected call of GetHintStats.
func (mr *MockIntegrationMockRecorder) GetHintStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHintStats", reflect.TypeOf((*MockIntegration)(nil).GetHintStats))
}

// GetSessionContext mocks base method.
func (m *MockIntegration) GetSessionContext(ctx context.Context, projectManager manager.ProjectManager, sessionManager session.SessionManager) (*hints.SessionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionContext", ctx, projectManager, sessionManager)
	ret0, _ := ret[0].(*hints.SessionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionContext indicates an expected call of GetSessionContext.
func (mr *MockIntegrationMockRecorder) GetSessionContext(ctx, projectManager, sessionManager any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionContext", reflect.TypeOf((*MockIntegration)(nil).GetSessionContext), ctx, projectManager, sessionManager)
}

// WrapToolResponse mocks base method.
func (m *MockIntegration) WrapToolResponse(response any, arg1 []hints.Hint) any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrapToolResponse", response, arg1)
	ret0, _ := ret[0].(any)
	return ret0
}

// WrapToolResponse indicates an expected call of WrapToolResponse.
func (mr *MockIntegrationMockRecorder) WrapToolResponse(response, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrapToolResponse", reflect.TypeOf((*MockIntegration)(nil).WrapToolResponse), response, arg1)
}
