// Code generated by MockGen. DO NOT EDIT.
// Source: internal/session/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/session/interface.go -destination=internal/mocks/mock_session_manager.go -package=mocks Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	session "github.com/denkhaus/knot/v2/internal/session"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// CleanupExpiredSessions mocks base method.
func (m *MockManager) CleanupExpiredSessions(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredSessions", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockManagerMockRecorder) CleanupExpiredSessions(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockManager)(nil).CleanupExpiredSessions), ctx, timeout)
}

// ClearProject mocks base method.
func (m *MockManager) ClearProject(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearProject", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearProject indicates an expected call of ClearProject.
func (mr *MockManagerMockRecorder) ClearProject(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearProject", reflect.TypeOf((*MockManager)(nil).ClearProject), sessionID)
}

// CloseAll mocks base method.
func (m *MockManager) CloseAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAll indicates an expected call of CloseAll.
func (mr *MockManagerMockRecorder) CloseAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAll", reflect.TypeOf((*MockManager)(nil).CloseAll), ctx)
}

// CreateSession mocks base method.
func (m *MockManager) CreateSession(clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockManagerMockRecorder) CreateSession(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockManager)(nil).CreateSession), clientID)
}

// CreateSessionWithID mocks base method.
func (m *MockManager) CreateSessionWithID(sessionID uuid.UUID, clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionWithID", sessionID, clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionWithID indicates an expected call of CreateSessionWithID.
func (mr *MockManagerMockRecorder) CreateSessionWithID(sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionWithID", reflect.TypeOf((*MockManager)(nil).CreateSessionWithID), sessionID, clientID)
}

// DeleteSession mocks base method.
func (m *MockManager) DeleteSession(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockManagerMockRecorder) DeleteSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockManager)(nil).DeleteSession), sessionID)
}

// GetProject mocks base method.
func (m *MockManager) GetProject(sessionID uuid.UUID) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", sessionID)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockManagerMockRecorder) GetProject(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockManager)(nil).GetProject), sessionID)
}

// GetSession mocks base method.
func (m *MockManager) GetSession(sessionID uuid.UUID) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockManagerMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockManager)(nil).GetSession), sessionID)
}

// GetSessionByClientID mocks base method.
func (m *MockManager) GetSessionByClientID(clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByClientID", clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByClientID indicates an expected call of GetSessionByClientID.
func (mr *MockManagerMockRecorder) GetSessionByClientID(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByClientID", reflect.TypeOf((*MockManager)(nil).GetSessionByClientID), clientID)
}

// GetSessionCount mocks base method.
func (m *MockManager) GetSessionCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSessionCount indicates an expected call of GetSessionCount.
func (mr *MockManagerMockRecorder) GetSessionCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionCount", reflect.TypeOf((*MockManager)(nil).GetSessionCount))
}

// ListSessions mocks base method.
func (m *MockManager) ListSessions() []*session.SessionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions")
	ret0, _ := ret[0].([]*session.SessionContext)
	return ret0
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockManagerMockRecorder) ListSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockManager)(nil).ListSessions))
}

// SetProject mocks base method.
func (m *MockManager) SetProject(sessionID, projectID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProject", sessionID, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProject indicates an expected call of SetProject.
func (mr *MockManagerMockRecorder) SetProject(sessionID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProject", reflect.TypeOf((*MockManager)(nil).SetProject), sessionID, projectID)
}

// ValidateSession mocks base method.
func (m *MockManager) ValidateSession(sessionID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockManagerMockRecorder) ValidateSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockManager)(nil).ValidateSession), sessionID)
}
