// Code generated by MockGen. DO NOT EDIT.
// Source: ../session/interface.go
//
// Generated by this command:
//
//	mockgen -source=../session/interface.go -destination=mock_session_manager.go -package=mocks Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	session "github.com/denkhaus/knot/v2/internal/session"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// CleanupExpiredSessions mocks base method.
func (m *MockSessionManager) CleanupExpiredSessions(ctx context.Context, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredSessions", ctx, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockSessionManagerMockRecorder) CleanupExpiredSessions(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockSessionManager)(nil).CleanupExpiredSessions), ctx, timeout)
}

// ClearProject mocks base method.
func (m *MockSessionManager) ClearProject(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearProject", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearProject indicates an expected call of ClearProject.
func (mr *MockSessionManagerMockRecorder) ClearProject(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearProject", reflect.TypeOf((*MockSessionManager)(nil).ClearProject), sessionID)
}

// CloseAll mocks base method.
func (m *MockSessionManager) CloseAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAll indicates an expected call of CloseAll.
func (mr *MockSessionManagerMockRecorder) CloseAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAll", reflect.TypeOf((*MockSessionManager)(nil).CloseAll), ctx)
}

// CreateSession mocks base method.
func (m *MockSessionManager) CreateSession(clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionManagerMockRecorder) CreateSession(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionManager)(nil).CreateSession), clientID)
}

// CreateSessionWithID mocks base method.
func (m *MockSessionManager) CreateSessionWithID(sessionID uuid.UUID, clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionWithID", sessionID, clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionWithID indicates an expected call of CreateSessionWithID.
func (mr *MockSessionManagerMockRecorder) CreateSessionWithID(sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionWithID", reflect.TypeOf((*MockSessionManager)(nil).CreateSessionWithID), sessionID, clientID)
}

// DeleteSession mocks base method.
func (m *MockSessionManager) DeleteSession(sessionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionManagerMockRecorder) DeleteSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionManager)(nil).DeleteSession), sessionID)
}

// GetProject mocks base method.
func (m *MockSessionManager) GetProject(sessionID uuid.UUID) (*uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProject", sessionID)
	ret0, _ := ret[0].(*uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockSessionManagerMockRecorder) GetProject(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockSessionManager)(nil).GetProject), sessionID)
}

// GetSession mocks base method.
func (m *MockSessionManager) GetSession(sessionID uuid.UUID) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", sessionID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionManagerMockRecorder) GetSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionManager)(nil).GetSession), sessionID)
}

// GetSessionByClientID mocks base method.
func (m *MockSessionManager) GetSessionByClientID(clientID string) (*session.SessionContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByClientID", clientID)
	ret0, _ := ret[0].(*session.SessionContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByClientID indicates an expected call of GetSessionByClientID.
func (mr *MockSessionManagerMockRecorder) GetSessionByClientID(clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByClientID", reflect.TypeOf((*MockSessionManager)(nil).GetSessionByClientID), clientID)
}

// GetSessionCount mocks base method.
func (m *MockSessionManager) GetSessionCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSessionCount indicates an expected call of GetSessionCount.
func (mr *MockSessionManagerMockRecorder) GetSessionCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionCount", reflect.TypeOf((*MockSessionManager)(nil).GetSessionCount))
}

// ListSessions mocks base method.
func (m *MockSessionManager) ListSessions() []*session.SessionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessions")
	ret0, _ := ret[0].([]*session.SessionContext)
	return ret0
}

// ListSessions indicates an expected call of ListSessions.
func (mr *MockSessionManagerMockRecorder) ListSessions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessions", reflect.TypeOf((*MockSessionManager)(nil).ListSessions))
}

// SetActor mocks base method.
func (m *MockSessionManager) SetActor(sessionID uuid.UUID, actor string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActor", sessionID, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActor indicates an expected call of SetActor.
func (mr *MockSessionManagerMockRecorder) SetActor(sessionID, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActor", reflect.TypeOf((*MockSessionManager)(nil).SetActor), sessionID, actor)
}

// SetProject mocks base method.
func (m *MockSessionManager) SetProject(sessionID, projectID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProject", sessionID, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProject indicates an expected call of SetProject.
func (mr *MockSessionManagerMockRecorder) SetProject(sessionID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProject", reflect.TypeOf((*MockSessionManager)(nil).SetProject), sessionID, projectID)
}

// ValidateSession mocks base method.
func (m *MockSessionManager) ValidateSession(sessionID uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockSessionManagerMockRecorder) ValidateSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockSessionManager)(nil).ValidateSession), sessionID)
}
