// Code generated by MockGen. DO NOT EDIT.
// Source: ../sync/shared/data_serializer.go
//
// Generated by this command:
//
//	mockgen -source=../sync/shared/data_serializer.go -destination=mock_sync_data_serializer.go -package=mocks SyncDataSerializer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	shared "github.com/denkhaus/knot/v2/internal/sync/shared"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncDataSerializer is a mock of SyncDataSerializer interface.
type MockSyncDataSerializer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncDataSerializerMockRecorder
	isgomock struct{}
}

// MockSyncDataSerializerMockRecorder is the mock recorder for MockSyncDataSerializer.
type MockSyncDataSerializerMockRecorder struct {
	mock *MockSyncDataSerializer
}

// NewMockSyncDataSerializer creates a new mock instance.
func NewMockSyncDataSerializer(ctrl *gomock.Controller) *MockSyncDataSerializer {
	mock := &MockSyncDataSerializer{ctrl: ctrl}
	mock.recorder = &MockSyncDataSerializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncDataSerializer) EXPECT() *MockSyncDataSerializerMockRecorder {
	return m.recorder
}

// CompareSize mocks base method.
func (m *MockSyncDataSerializer) CompareSize(data any) (int, int, float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareSize", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(float64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CompareSize indicates an expected call of CompareSize.
func (mr *MockSyncDataSerializerMockRecorder) CompareSize(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareSize", reflect.TypeOf((*MockSyncDataSerializer)(nil).CompareSize), data)
}

// DeserializeRequest mocks base method.
func (m *MockSyncDataSerializer) DeserializeRequest(data []byte, format string) (*shared.SyncRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeserializeRequest", data, format)
	ret0, _ := ret[0].(*shared.SyncRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeserializeRequest indicates an expected call of DeserializeRequest.
func (mr *MockSyncDataSerializerMockRecorder) DeserializeRequest(data, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeserializeRequest", reflect.TypeOf((*MockSyncDataSerializer)(nil).DeserializeRequest), data, format)
}

// DeserializeResponse mocks base method.
func (m *MockSyncDataSerializer) DeserializeResponse(data []byte, format string) (*shared.SyncResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeserializeResponse", data, format)
	ret0, _ := ret[0].(*shared.SyncResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeserializeResponse indicates an expected call of DeserializeResponse.
func (mr *MockSyncDataSerializerMockRecorder) DeserializeResponse(data, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeserializeResponse", reflect.TypeOf((*MockSyncDataSerializer)(nil).DeserializeResponse), data, format)
}

// DetectFormat mocks base method.
func (m *MockSyncDataSerializer) DetectFormat(contentType string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectFormat", contentType)
	ret0, _ := ret[0].(string)
	return ret0
}

// DetectFormat indicates an expected call of DetectFormat.
func (mr *MockSyncDataSerializerMockRecorder) DetectFormat(contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectFormat", reflect.TypeOf((*MockSyncDataSerializer)(nil).DetectFormat), contentType)
}

// GetContentType mocks base method.
func (m *MockSyncDataSerializer) GetContentType(format string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentType", format)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetContentType indicates an expected call of GetContentType.
func (mr *MockSyncDataSerializerMockRecorder) GetContentType(format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentType", reflect.TypeOf((*MockSyncDataSerializer)(nil).GetContentType), format)
}

// SerializeErrorResponse mocks base method.
func (m *MockSyncDataSerializer) SerializeErrorResponse(errResp *shared.ErrorResponse, format string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeErrorResponse", errResp, format)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SerializeErrorResponse indicates an expected call of SerializeErrorResponse.
func (mr *MockSyncDataSerializerMockRecorder) SerializeErrorResponse(errResp, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeErrorResponse", reflect.TypeOf((*MockSyncDataSerializer)(nil).SerializeErrorResponse), errResp, format)
}

// SerializeRequest mocks base method.
func (m *MockSyncDataSerializer) SerializeRequest(req *shared.SyncRequest, format string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeRequest", req, format)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SerializeRequest indicates an expected call of SerializeRequest.
func (mr *MockSyncDataSerializerMockRecorder) SerializeRequest(req, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeRequest", reflect.TypeOf((*MockSyncDataSerializer)(nil).SerializeRequest), req, format)
}

// SerializeResponse mocks base method.
func (m *MockSyncDataSerializer) SerializeResponse(resp *shared.SyncResponse, format string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerializeResponse", resp, format)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SerializeResponse indicates an expected call of SerializeResponse.
func (mr *MockSyncDataSerializerMockRecorder) SerializeResponse(resp, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerializeResponse", reflect.TypeOf((*MockSyncDataSerializer)(nil).SerializeResponse), resp, format)
}

// ValidateRequest mocks base method.
func (m *MockSyncDataSerializer) ValidateRequest(req *shared.SyncRequest) shared.ValidationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRequest", req)
	ret0, _ := ret[0].(shared.ValidationResult)
	return ret0
}

// ValidateRequest indicates an expected call of ValidateRequest.
func (mr *MockSyncDataSerializerMockRecorder) ValidateRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRequest", reflect.TypeOf((*MockSyncDataSerializer)(nil).ValidateRequest), req)
}

// ValidateResponse mocks base method.
func (m *MockSyncDataSerializer) ValidateResponse(resp *shared.SyncResponse) shared.ValidationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateResponse", resp)
	ret0, _ := ret[0].(shared.ValidationResult)
	return ret0
}

// ValidateResponse indicates an expected call of ValidateResponse.
func (mr *MockSyncDataSerializerMockRecorder) ValidateResponse(resp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateResponse", reflect.TypeOf((*MockSyncDataSerializer)(nil).ValidateResponse), resp)
}
