// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sync/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/sync/interfaces.go -destination=internal/mocks/mock_sync_manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sync "github.com/denkhaus/knot/v2/internal/sync"
	shared "github.com/denkhaus/knot/v2/internal/sync/shared"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncManager is a mock of SyncManager interface.
type MockSyncManager struct {
	ctrl     *gomock.Controller
	recorder *MockSyncManagerMockRecorder
	isgomock struct{}
}

// MockSyncManagerMockRecorder is the mock recorder for MockSyncManager.
type MockSyncManagerMockRecorder struct {
	mock *MockSyncManager
}

// NewMockSyncManager creates a new mock instance.
func NewMockSyncManager(ctrl *gomock.Controller) *MockSyncManager {
	mock := &MockSyncManager{ctrl: ctrl}
	mock.recorder = &MockSyncManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncManager) EXPECT() *MockSyncManagerMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockSyncManager) Sync(ctx context.Context, projectID uuid.UUID, direction shared.SyncDirection) (*sync.SyncResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, projectID, direction)
	ret0, _ := ret[0].(*sync.SyncResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockSyncManagerMockRecorder) Sync(ctx, projectID, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockSyncManager)(nil).Sync), ctx, projectID, direction)
}
