version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - nakedret
    - gocritic
    - goconst

linters-settings:
  funlen:
    lines: 120
    statements: 50

  revive:
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning

formatters:
  enable:
    - gofmt