version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - gocyclo
    - revive
    - goconst
    - funlen

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
    settings:
      dupl: false
  funlen:
    lines: 500
    statements: 100

formatters:
  enable:
    - gofmt