#!/bin/bash
# Bash completion script for knot
# Generated by knot completion command

_knot_completion() {
    local cur prev words cword
    _init_completion || return

    # Available commands
    local commands="project task template dependency config health validate ready blocked actionable breakdown get-started completion"

    # Main command completion
    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        return
    fi

    # Command-specific completions
    local cmd="${words[1]}"
    case "$cmd" in
        project|task|template|dependency|config|health|validate)
            COMPREPLY=($(compgen -W "--json --help -h" -- "$cur"))
            ;;
        ready|blocked)
            COMPREPLY=($(compgen -W "--limit --json --help -h" -- "$cur"))
            ;;
        actionable)
            COMPREPLY=($(compgen -W "--strategy --allow-parent-with-subtasks --prefer-pending --verbose --json --help -h" -- "$cur"))
            ;;
        breakdown)
            COMPREPLY=($(compgen -W "--limit --threshold --json --quiet --help -h" -- "$cur"))
            ;;
        completion)
            COMPREPLY=($(compgen -W "bash zsh --help -h" -- "$cur"))
            ;;
        *)
            # Default flag completion for any command
            COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
            ;;
    esac

    # Dynamic completion for project and task IDs
    _knot_complete_ids() {
        local type=$1
        local ids
        if [[ "$type" == "project" ]]; then
            ids=$(knot project list --json 2>/dev/null | jq -r '.[].id // empty' 2>/dev/null || echo "")
        elif [[ "$type" == "task" ]]; then
            ids=$(knot task list --json 2>/dev/null | jq -r '.[].id // empty' 2>/dev/null || echo "")
        fi
        COMPREPLY=($(compgen -W "$ids" -- "$cur"))
    }

    # Special completion for specific flags that expect IDs
    case "${prev}" in
        --id|--project-id|--parent-id)
            _knot_complete_ids task
            return
            ;;
    esac
}

# Register completion
complete -F _knot_completion knot