#compdef knot
# Zsh completion script for knot
# Generated by knot completion command

_knot() {
    local -a commands
    commands=(
        'project:Project management commands'
        'task:Task management commands'
        'template:Task template management commands'
        'dependency:Task dependency management'
        'config:Configuration management'
        'health:Database health and connectivity checks'
        'validate:Task state validation and transition checks'
        'ready:Show tasks with no blockers'
        'blocked:Show tasks blocked by dependencies'
        'actionable:Find the next actionable task'
        'breakdown:Find tasks that need breakdown'
        'get-started:Get started guide'
        'completion:Generate shell completion scripts'
    )

    local -a project_subcommands
    project_subcommands=(
        'list:List all projects'
        'create:Create a new project'
        'select:Select a project'
        'delete:Delete a project'
        'get:Get project details'
        'get-selected:Show selected project'
        'clear-selection:Clear project selection'
        'clear-search:Clear project search'
    )

    local -a task_subcommands
    task_subcommands=(
        'list:List tasks in current project'
        'create:Create a new task'
        'get:Get task details'
        'update-state:Update task state'
        'delete:Delete a task'
        'actionable:Get next actionable task'
        'breakdown:Find tasks needing breakdown'
    )

    local -a actionable_strategies
    actionable_strategies=(
        'dependency-aware:Prioritizes tasks that unblock others'
        'depth-first:Complete subtasks before moving to other branches'
        'priority:Focus on high-priority tasks first'
        'creation-order:Original knot behavior (oldest first)'
        'critical-path:Focus on tasks affecting project timeline'
    )

    local -a completion_shells
    completion_shells=(
        'bash:Generate bash completion'
        'zsh:Generate zsh completion'
    )

    if [[ CURRENT -eq 2 ]]; then
        _describe 'command' commands
        return
    fi

    local cmd=$words[2]
    case $cmd in
        project)
            if [[ CURRENT -eq 3 ]]; then
                _describe 'subcommand' project_subcommands
            else
                _arguments \
                    '--json[Output in JSON format]' \
                    '--help[Show help]' \
                    '-h[Show help]'
            fi
            ;;
        task)
            if [[ CURRENT -eq 3 ]]; then
                _describe 'subcommand' task_subcommands
            else
                _arguments \
                    '--json[Output in JSON format]' \
                    '--help[Show help]' \
                    '-h[Show help]'
            fi
            ;;
        actionable)
            _arguments \
                '--strategy[Selection strategy]:strategy:_actionable_strategies' \
                '--allow-parent-with-subtasks[Allow selection of parent tasks even when subtasks exist]' \
                '--prefer-pending[Prefer pending tasks over in-progress tasks]' \
                '--verbose[Show detailed selection reasoning and alternatives]' \
                '--json[Output result as JSON]' \
                '--help[Show help]' \
                '-h[Show help]'
            ;;
        ready|blocked)
            _arguments \
                '--limit[Maximum number of tasks to show]:limit:' \
                '--json[Output in JSON format]' \
                '--help[Show help]' \
                '-h[Show help]'
            ;;
        breakdown)
            _arguments \
                '--limit[Maximum number of tasks to show]:limit:' \
                '--threshold[Complexity threshold for breakdown]:threshold:(8 9 10)' \
                '--json[Output in JSON format]' \
                '--quiet[Suppress output]' \
                '--help[Show help]' \
                '-h[Show help]'
            ;;
        completion)
            if [[ CURRENT -eq 3 ]]; then
                _describe 'shell' completion_shells
            else
                _arguments \
                    '--help[Show help]' \
                    '-h[Show help]'
            fi
            ;;
        *)
            _arguments \
                '--help[Show help]' \
                '-h[Show help]'
            ;;
    esac

    # Dynamic completion for project and task IDs
    _knot_ids() {
        local type=$1
        local ids=()
        if [[ "$type" == "project" ]]; then
            ids=(${(f)"$(knot project list --json 2>/dev/null | jq -r '.[].id // empty' 2>/dev/null)"})
        elif [[ "$type" == "task" ]]; then
            ids=(${(f)"$(knot task list --json 2>/dev/null | jq -r '.[].id // empty' 2>/dev/null)"})
        fi
        _describe "${type} IDs" ids
    }

    # Special completion for ID arguments
    if [[ "$words[CURRENT-1]" == "--id" ]] || \
       [[ "$words[CURRENT-1]" == "--project-id" ]] || \
       [[ "$words[CURRENT-1]" == "--parent-id" ]]; then
        _knot_ids task
    fi
}

_knot_actionable_strategies() {
    local -a strategies
    strategies=(
        'dependency-aware'
        'depth-first'
        'priority'
        'creation-order'
        'critical-path'
    )
    _describe 'strategy' strategies
}

_knot "$@"