// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/denkhaus/knot/internal/repository/sqlite/ent/project"
	"github.com/denkhaus/knot/internal/repository/sqlite/ent/task"
	"github.com/google/uuid"
)

// ProjectCreate is the builder for creating a Project entity.
type ProjectCreate struct {
	config
	mutation *ProjectMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *ProjectCreate) SetTitle(v string) *ProjectCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ProjectCreate) SetDescription(v string) *ProjectCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableDescription(v *string) *ProjectCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *ProjectCreate) SetState(v project.State) *ProjectCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableState(v *project.State) *ProjectCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProjectCreate) SetCreatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProjectCreate) SetUpdatedAt(v time.Time) *ProjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableUpdatedAt(v *time.Time) *ProjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTotalTasks sets the "total_tasks" field.
func (_c *ProjectCreate) SetTotalTasks(v int) *ProjectCreate {
	_c.mutation.SetTotalTasks(v)
	return _c
}

// SetNillableTotalTasks sets the "total_tasks" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableTotalTasks(v *int) *ProjectCreate {
	if v != nil {
		_c.SetTotalTasks(*v)
	}
	return _c
}

// SetCompletedTasks sets the "completed_tasks" field.
func (_c *ProjectCreate) SetCompletedTasks(v int) *ProjectCreate {
	_c.mutation.SetCompletedTasks(v)
	return _c
}

// SetNillableCompletedTasks sets the "completed_tasks" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCompletedTasks(v *int) *ProjectCreate {
	if v != nil {
		_c.SetCompletedTasks(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *ProjectCreate) SetProgress(v float64) *ProjectCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableProgress(v *float64) *ProjectCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ProjectCreate) SetCreatedBy(v string) *ProjectCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableCreatedBy(v *string) *ProjectCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ProjectCreate) SetUpdatedBy(v string) *ProjectCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableUpdatedBy(v *string) *ProjectCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ProjectCreate) SetID(v uuid.UUID) *ProjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ProjectCreate) SetNillableID(v *uuid.UUID) *ProjectCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *ProjectCreate) AddTaskIDs(ids ...uuid.UUID) *ProjectCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *ProjectCreate) AddTasks(v ...*Task) *ProjectCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_c *ProjectCreate) Mutation() *ProjectMutation {
	return _c.mutation
}

// Save creates the Project in the database.
func (_c *ProjectCreate) Save(ctx context.Context) (*Project, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProjectCreate) SaveX(ctx context.Context) *Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProjectCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := project.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := project.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := project.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		v := project.DefaultTotalTasks
		_c.mutation.SetTotalTasks(v)
	}
	if _, ok := _c.mutation.CompletedTasks(); !ok {
		v := project.DefaultCompletedTasks
		_c.mutation.SetCompletedTasks(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := project.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := project.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProjectCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Project.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := project.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Project.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Project.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := project.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Project.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Project.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Project.updated_at"`)}
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		return &ValidationError{Name: "total_tasks", err: errors.New(`ent: missing required field "Project.total_tasks"`)}
	}
	if v, ok := _c.mutation.TotalTasks(); ok {
		if err := project.TotalTasksValidator(v); err != nil {
			return &ValidationError{Name: "total_tasks", err: fmt.Errorf(`ent: validator failed for field "Project.total_tasks": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompletedTasks(); !ok {
		return &ValidationError{Name: "completed_tasks", err: errors.New(`ent: missing required field "Project.completed_tasks"`)}
	}
	if v, ok := _c.mutation.CompletedTasks(); ok {
		if err := project.CompletedTasksValidator(v); err != nil {
			return &ValidationError{Name: "completed_tasks", err: fmt.Errorf(`ent: validator failed for field "Project.completed_tasks": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "Project.progress"`)}
	}
	if v, ok := _c.mutation.Progress(); ok {
		if err := project.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "Project.progress": %w`, err)}
		}
	}
	return nil
}

func (_c *ProjectCreate) sqlSave(ctx context.Context) (*Project, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProjectCreate) createSpec() (*Project, *sqlgraph.CreateSpec) {
	var (
		_node = &Project{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(project.Table, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(project.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(project.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(project.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TotalTasks(); ok {
		_spec.SetField(project.FieldTotalTasks, field.TypeInt, value)
		_node.TotalTasks = value
	}
	if value, ok := _c.mutation.CompletedTasks(); ok {
		_spec.SetField(project.FieldCompletedTasks, field.TypeInt, value)
		_node.CompletedTasks = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(project.FieldProgress, field.TypeFloat64, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(project.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(project.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectCreateBulk is the builder for creating many Project entities in bulk.
type ProjectCreateBulk struct {
	config
	err      error
	builders []*ProjectCreate
}

// Save creates the Project entities in the database.
func (_c *ProjectCreateBulk) Save(ctx context.Context) ([]*Project, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Project, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProjectCreateBulk) SaveX(ctx context.Context) []*Project {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
