// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectContext is the predicate function for projectcontext builders.
type ProjectContext func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskDependency is the predicate function for taskdependency builders.
type TaskDependency func(*sql.Selector)
